[package]
name = "rusty_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bench = "0.2"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit-sys = "0.4"
